services:
  etemaro:
    build:
      context: .
      dockerfile: Dockerfile
    image: etemaro:prod
    command: pnpm run start
    env_file: .env
    environment:
      - USER_CONFIG_PATH
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    restart: unless-stopped

networks:
  default:
    name: etemaro-prod
