services:
  etemaro:
    build:
      context: .
      dockerfile: Dockerfile
    image: etemaro:dev
    command: pnpm run dev
    env_file: .env
    volumes:
      - ./packages:/app/packages
      - /app/node_modules
      - /app/packages/core/node_modules
      - /app/packages/daemon/node_modules
      - /app/packages/cli/node_modules
      - ./config:/app/config
      - ./data:/app/data
    restart: unless-stopped

networks:
  default:
    name: etemaro-dev
