services:
  meridian:
    build:
      context: .
      dockerfile: Dockerfile
    image: meridian:prod
    command: pnpm run start
    env_file: .env
    volumes:
      - ./packages:/app/packages
      - ./config:/app/config
      - ./data:/app/data
    restart: unless-stopped

networks:
  default:
    name: meridian-prod
