import type { UserConfigRaw } from './schema.js';

export const DEFAULT_USER_CONFIG: UserConfigRaw = {
  _version: 3,
  preset: 'custom',
  agentId: '',

  connection: {
    description:
      'Network endpoints, API credentials, wallet key, LLM provider settings, and runtime mode. These values are also propagated to environment variables on startup.',
    rpcUrl: 'https://pump.helius-rpc.com',
    walletPrivateKey: 'env.WALLET_PRIVATE_KEY',
    heliusApiKey: 'env.HELIUS_API_KEY',
    telegramBotToken: 'env.TELEGRAM_BOT_TOKEN',
    telegramChatId: 'env.TELEGRAM_CHAT_ID',
    telegramAllowedUserIds: 'env.TELEGRAM_ALLOWED_USER_IDS',
    dryRun: true,
  },

  risk: {
    description: 'Global capital limits that cap exposure regardless of how many positions look attractive.',
    maxPositions: 1,
    maxDeployAmount: 50,
  },

  screening: {
    description: 'Filters applied when scanning for new pool candidates. Tighten these to reduce noise; loosen them to explore more pools.',
    entrySource: 'market',
    timeframe: '5m',
    category: 'trending',
    excludeHighSupplyConcentration: true,
    minTvl: 10000,
    maxTvl: 150000,
    minVolume: 500,
    minOrganic: 60,
    minQuoteOrganic: 60,
    minHolders: 500,
    minMcap: 150000,
    maxMcap: 10000000,
    minBinStep: 80,
    maxBinStep: 125,
    minFeeActiveTvlRatio: 0.02,
    minTokenFeesSol: 30,
    useDiscordSignals: false,
    discordSignalMode: 'merge',
    avoidPvpSymbols: true,
    blockPvpSymbols: false,
    maxBotHoldersPct: 30,
    maxTop10Pct: 60,
    loneCandidateMinDegen: 50,
    allowedLaunchpads: [],
    blockedLaunchpads: [],
    minTokenAgeHours: null,
    maxTokenAgeHours: null,
  },

  management: {
    description: 'Rules for managing open positions: claims, rebalances, stop-loss, take-profit, trailing stops, and cooldowns.',
    minClaimAmount: 5,
    autoSwapAfterClaim: true,
    autoSwapRetryAttempts: 3,
    autoSwapRetryDelayMs: 3000,
    haltOnSwapFailure: true,
    maxFailedSwapsBeforeHalt: 5,
    autoSwapInterSwapDelayMs: 1500,
    outOfRangeBinsToClose: 10,
    outOfRangeWaitMinutes: 30,
    oorCooldownTriggerCount: 3,
    oorCooldownHours: 12,
    repeatDeployCooldownEnabled: true,
    repeatDeployCooldownTriggerCount: 3,
    repeatDeployCooldownHours: 12,
    repeatDeployCooldownScope: 'token',
    repeatDeployCooldownMinFeeEarnedPct: 0,
    minVolumeToRebalance: 1000,
    stopLossPct: -50,
    takeProfitPct: 5,
    minFeePerTvl24h: 7,
    minAgeBeforeYieldCheck: 60,
    minSolToOpen: 0.55,
    deployAmountSol: 0.1,
    gasReserve: 0.1,
    positionSizePct: 0.35,
    trailingTakeProfit: true,
    trailingTriggerPct: 3,
    trailingDropPct: 1.5,
    pnlSanityMaxDiffPct: 5,
    solMode: false,
  },

  strategy: {
    description: 'LP bin placement strategy. Determines how liquidity is distributed relative to the active price bin.',
    activeStrategyId: 'single_sided_reseed',
    strategyMeteora: 'bid_ask',
    minBinsBelow: 35,
    maxBinsBelow: 69,
    defaultBinsBelow: 69,
    minSafeBinsBelow: 10,
  },

  schedule: {
    description: 'Cadence for background loops. Keep managementIntervalMin shorter than outOfRangeWaitMinutes so the agent can act in time.',
    managementIntervalMin: 10,
    screeningIntervalMin: 30,
    healthCheckIntervalMin: 60,
  },

  llm: {
    description: 'LLM inference parameters and per-role model overrides.',
    baseUrl: 'env.LLM_BASE_URL',
    apiKey: 'env.LLM_API_KEY',
    temperature: 0.373,
    maxTokens: 10000,
    maxSteps: 20,
    defaultModel: 'env.LLM_MODEL',
    generalModel: 'env.LLM_MODEL',
    managementModel: 'env.LLM_MODEL',
    screeningModel: 'env.LLM_MODEL',
  },

  darwin: {
    description:
      'Auto-evolution of signal weights based on closed-position outcomes. Weights are boosted for winning signals and decayed for losers.',
    enabled: true,
    windowDays: 60,
    recalcEvery: 5,
    boostFactor: 1.05,
    decayFactor: 0.95,
    weightFloor: 0.3,
    weightCeiling: 2.5,
    minSamples: 10,
  },

  hiveMind: {
    description: 'Collective learning layer. Pulls shared lessons and presets from a remote HiveMind backend; pushes local lessons back.',
    enabled: true,
    url: 'https://api.agentmeridian.xyz',
    apiKey: 'env.DEFAULT_AGENT_MERIDIAN_PUBLIC_KEY',
    agentId: '',
    pullMode: 'auto',
  },

  api: {
    description: 'External API integrations. Enable only the services needed for research, position lookup, or relay execution.',
    meridian: {
      description: 'Agent Meridian API for study data, open-position lookup, and optional relay execution.',
      enabled: true,
      url: 'https://api.agentmeridian.xyz/api',
      publicApiKey: 'env.DEFAULT_AGENT_MERIDIAN_PUBLIC_KEY',
      lpAgentRelayEnabled: false,
    },
    lpAgent: {
      description: 'LPAgent API for external open-position data. Enable it and provide LPAGENT_API_KEY when this data source is required.',
      enabled: false,
      url: 'https://api.lpagent.io/open-api/v1',
      apiKey: 'env.LPAGENT_API_KEY',
    },
  },

  pnl: {
    description: 'PnL tracking source, RPC endpoint, and polling cadence for position valuation.',
    source: 'rpc',
    rpcUrl: 'https://pump.helius-rpc.com',
    pollIntervalSec: 3,
    depositCacheTtlSec: 300,
    confirmTicks: 2,
  },

  opportunity: {
    description: 'Background opportunity poller that scans for new high-yield pools using smart-wallet and liquidity metrics.',
    enabled: true,
    pollIntervalSec: 45,
    limit: 10,
    minScore: 40,
    smartWalletScoreBonus: 20,
    targetVolRatio: 20,
    targetLpCount: 40,
    targetFeeRatio: 0.2,
    targetLiquidity: 20000,
  },

  gmgn: {
    description: 'Optional GMGN API integration used to provide the token-fee value for screening. Enable it only when GMGN_API_KEY is configured.',
    enabled: false,
    feeSource: 'gmgn',
    apiKey: 'env.GMGN_API_KEY',
    baseUrl: 'https://openapi.gmgn.ai',
    requestDelayMs: 2500,
    maxRetries: 2,
  },

  jupiter: {
    description: 'Jupiter swap API credentials and referral settings.',
    apiKey: 'env.JUPITER_API_KEY',
    referralAccount: '',
    referralFeeBps: 50,
  },

  chartIndicators: {
    description: 'Technical analysis indicators (RSI, supertrend) used as entry/exit signals.',
    enabled: false,
    entryPreset: 'supertrend_break',
    exitPreset: 'supertrend_break',
    rsiLength: 2,
    intervals: ['5_MINUTE'],
    candles: 298,
    rsiOversold: 30,
    rsiOverbought: 80,
    requireAllIntervals: false,
  },
};

export const defaultUserConfigStr = JSON.stringify(DEFAULT_USER_CONFIG, null, 2);
